[project]
name = "bootcamp-python"
version = "0.1.0"
description = ""
authors = [
    {name = "Gabrielle",email = "gabrielle.urcioli@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "pandera (>=0.31.1,<0.32.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "fastparquet (>=2026.5.0,<2027.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "sqlalchemy (>=2.0.50,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
